name: aurora_fv
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - microsoft-aurora
    - xarray
    - cdsapi
    - netcdf4 
    - matplotlib
    - zarr
    - gcsfs
    - dask
    - kornia
